### ISSUE TITLE
Pickaxe missing from items

### ISSUE THREAD

**Issue by MillionthOdin16** [tostesdaniel/rust-conveyor-filters#152]
The metal pickaxe (as opposed to Stone pickaxe or salvaged) is missing from the selectable items. When attempting to import it to the website, it crashes.

**Comment by tostesdaniel** [comment]
Will look into that. Thank you for letting me know.

**Comment by tostesdaniel** [comment]
Sorry for the delays. It was a simple fix. Thank you for the feedback! 😊
