### ISSUE TITLE
longsleeve t-shirt and snow jacket missing from item list

### ISSUE THREAD

**Issue by jhesso** [tostesdaniel/rust-conveyor-filters#196]
as title says. the longsleeve t-shirt and snow jacket seems to be missing from the item list and cannot be added to the filter list

**Comment by tostesdaniel** [comment]
Hey there! I'll take a look and make the necessary adjustments. Expect a followup answer soon.

**Comment by tostesdaniel** [comment]
Sorry for the delay. I was finishing an on-going bug hunt.

You may now create filters with Longsleeve T-Shirt and Snow Jacket. Thanks for letting me know.

Happy sorting!
